### ISSUE TITLE
セキュリティ設定の方法

### ISSUE THREAD

**Issue by kotoyukihana** [thinreports/thinreports-rails-example#197]
サンプルコードのapp/reports/tasks_report.rbの def buildでPDFのパスワード設定等のセキュリティを設定することはできますか？
当該設定は.pdf.thinrepirtsファイルを使用して行うのでしょうか？
またその場合.pdf.thinrepirtsファイルを使用し、send_dataによるダウンロードを行うことは可能でしょうか？

**Comment by hidakatsuya** [comment]
> サンプルコードのapp/reports/tasks_report.rbの def buildでPDFのパスワード設定等のセキュリティを設定することはできますか？

`TasksReport` は、単に Thinreports を使った自前のPDF生成クラスですので、 Thinreports のパスワード設定の方法（以下）に従って実装すればできます。
https://github.com/thinreports/thinreports-examples/tree/main/permission

> 当該設定は.pdf.thinrepirtsファイルを使用して行うのでしょうか？

`TasksReport` でも、`.pdf.thinreports` でもどちらでもできます。`.pdf.thinreports` での設定方法は以下を参照すると良いと思います。
https://github.com/takeshinoda/thinreports-rails#generate-options

> またその場合.pdf.thinrepirtsファイルを使用し、send_dataによるダウンロードを行うことは可能でしょうか？

以下を参考にしてください。
https://github.com/takeshinoda/thinreports-rails#example-to-download-pdf

**Comment by hidakatsuya** [comment]
こちら閉じますね。もし何か追加で質問などありましたら、ディスカッションの方からご質問ください。
